### ISSUE TITLE
broken link in intro deck

### ISSUE THREAD

**Issue by mamund** [dret/lectures#20]
this link:

https://tag-app-delivery.cncf.io/whitepapers/platform-eng-maturity-model/

on slide 8 of the introduction deck

returns 404

**Comment by dret** [comment]
On 2024-04-16 16:30, Mike Amundsen wrote:
> this link:
> https://tag-app-delivery.cncf.io/whitepapers/platform-eng-maturity-model/ <https://tag-app-delivery.cncf.io/whitepapers/platform-eng-maturity-model/>
> on slide 8 of the introduction deck
> returns 404

true, but CNCF broke this link this week. i let them know and hope they'll fix it. i cannot find that resource on their web site anymore.

**Comment by dret** [comment]
got confirmation that it's them and not me but that doesn't really make the link work again... let's see...

**Comment by mamund** [comment]
;( 

let's hope they get it fixed soon.

**Comment by dret** [comment]
They fixed it!
